language: python
sudo: false
dist: trusty
matrix:
 include:
  - python: 2.7
    env: TOXENV=py2
  - python: 3.8
    env: TOXENV=py3
  - python: pypy
    env: TOXENV=pypy2
  - python: pypy3
    env: TOXENV=pypy3
#before_install:
  # Install tor and chutney if doing functional tests
  #- if [[ $TEST == 'functional' ]]; then ./test/scripts/install-tor.sh; fi
  #- if [[ $TEST == 'functional' ]]; then source test/scripts/install-chutney.sh; fi
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
